title: Pathikreet Dutta
description: Oracle Cloud Architect | Cloud Native Consultant | Oracle FMW | DevOps Engineer | Emerging Technology Enthusiast
author: Pathikreet Dutta
avatar: /assets/DSC02334.JPG
theme: jekyll-theme-slate
