title: Pathikreet Dutta
description: Oracle Cloud Architect | Cloud Native Consultant | Oracle FMW | DevOps Engineer | Emerging Technology Enthusiast
author: Pathikreet Dutta
theme: jekyll-theme-slate
