title: Pathikreet Dutta
description: Oracle Cloud Architect | Cloud Native Consultant | Oracle FMW | DevOps Engineer | Emerging Technology Enthusiast
author: Pathikreet Dutta
avatar: https://github.com/pathikreet/pathikreet.github.io/blob/7c27ea9015c3482d779df1c203dc4599be5b3ed5/docs/assets/DSC02334.JPG
theme: jekyll-theme-slate
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
social-network-links:
  email: "pathikreet.dutta@outlook.com"
  github: pathikreet
  twitter: pathikreet
plugins:
  - jekyll-paginate
  - jekyll-sitemap
